### ISSUE TITLE
TypeError: __init__() missing 4 required positional arguments: 'genotypes', 'sample_pos', 'node_pos', and 'edges'

### ISSUE THREAD

**Issue by WeiYang-BAI** [jhmarcus/feems#1]
Hi, everyone.
I installed feems and ran the example by instruction here ( http://jhmarcus.com/feems/notebooks/getting-started.html ), everything seems perfect untill I setup the SpatialGraph object (step [12] in the instruction): 
Run:
sp_graph = SpatialGraph(genotypes, coord, grid, edges)

Return:
TypeError: __init__() missing 4 required positional arguments: 'genotypes', 'sample_pos', 'node_pos', and 'edges'

My python installed in conda was 3.8. Anyone could please help me out? many thanks!

**Comment by gaushi** [comment]
Hi,
I have exact same problem.
I have tried using Python3.6, Python 3.7 and Python3.8

TypeError: __init__() missing 4 required positional arguments: 'genotypes', 'sample_pos', 'node_pos', and 'edges'

Help will be much appreciated, Thanks!!

**Comment by gaushi** [comment]
@WeiYang-BAI : Try Python3.5, cartopy0.18
It worked for me

**Comment by WeiYang-BAI** [comment]
> @WeiYang-BAI : Try Python3.5, cartopy0.18
> It worked for me

@gaushi Many thanks! I'll try that.

**Comment by juanenciso14** [comment]
> @WeiYang-BAI : Try Python3.5, cartopy0.18
> It worked for me

Has anyone got it to work with python>3.7?

**Comment by MelinaGia** [comment]
I'm having the same issue! Has anyone gotten it to work with the most recent version of python?
